[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_quiz_rewards = "Ej4LLtFBrg8SXuSusmm5nHyqaMn4BZ31hyPGtLfQmA1P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://host.docker.internal:8899"
wallet = "./../../secret/authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
