global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'solana-quiz-node'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node:3000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'rules/*.yml'